# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67f4b0ead34c765540cb9d3446ea9bcf1ba2e9a02ec652547320686f8f250ca166c006b09e85db33eb422cb343971b7daee01f2cfed65401956ea39fcf8df4dd

test:
  secret_key_base: 701efab4335339c88b07dab6b1dba384ba588428cae9f64e4eddfa35fab845f6dcd5e9068acb02b862ea798374f7e5d25fe49b947fdd8aae40e2c62de49dcc29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
